name: Deploy Cloud Function with WIF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: "projects/937980401410/locations/global/workloadIdentityPools/github-pool-service-account-key/providers/github-provider"
        service_account: "github-actions-test@gcp-5ann01-sbx-devopspoc.iam.gserviceaccount.com"

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy send_notification \
          --runtime python310 \
          --trigger-topic my-topic2 \
          --entry-point send_notification \
          --source . \
          --region=us-central1 \
          --set-env-vars "username=omg-us-campaign-global,password=boDPlDfOhGswvRUd,sender=gcp_notification_sender@annalect.com,SMTP=mail.smtp2go.com,recipients=saikiran.madderla@annalect.com"
